import type { Metadata } from "next";
import React from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <SessionWrapper>
    <html lang="en">
      <body className="font-open-sans">
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  </SessionWrapper>
);

export default RootLayout;
